image: ruby:2.7-bullseye

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - gem install bundler
    - bundle install
  script:
    - bundle exec rspec
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always

deploy:
  stage: deploy
  before_script:
    - mkdir ~/.gem
    - echo "---" > ~/.gem/credentials
    - |
      echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems: '${CI_JOB_TOKEN}'" >> ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials # rubygems requires 0600 permissions on the credentials file
    - bash -x .gitlab/ci/init.sh
  script:
    - gem build fluent-plugin-parser_cef
    - gem push fluent-plugin-parser_cef-${CI_COMMIT_TAG}.gem --host ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems
  only:
    - tags
  except:
    - branches
