image: ruby:2.7-bullseye

before_script:
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
    - bundle exec rspec
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml