image: ruby:2.7-bullseye

before_script:
  - gem install bundler
  - bundle install
  # - mkdir ~/.gem
  - echo "---" > ~/.gem/credentials
  - |
    echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems: '${CI_JOB_TOKEN}'" >> ~/.gem/credentials
  - chmod 0600 ~/.gem/credentials # rubygems requires 0600 permissions on the credentials file

test:
  stage: test
  script:
    - bundle exec rspec
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always

deploy:
  script:
    - gem build my_gem
    - gem push my_gem-0.0.1.gem --host ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems
  only:
    - tags
  except:
    - branches